# Generated by Django 3.2.3 on 2021-05-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='real_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
